[project]
name = "example-5-baml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "baml-py>=0.77.0",
    "instructor>=1.7.2",
    "pydantic>=2.10.6",
]
